### ISSUE TITLE
Gradle Sync Failed

### ISSUE THREAD

**Issue by YimingLi-1996** [HMS-Core/hms-drive-clientdemo#2]
I cannot build the demo app in Android Studio.

Unable to find method 'org.gradle.api.file.ProjectLayout.fileProperty(Lorg/gradle/api/provider/Provider;)Lorg/gradle/api/file/RegularFileProperty;'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by Redreaming** [comment]
Try to update Android Gradle plugin to 3.3.1 or higher.
