### ISSUE TITLE
Why in 5.2.0.300 minSdkVersion was increased to 29?

### ISSUE THREAD

**Issue by d3p2dkop23fmopf32** [HMS-Core/hms-drive-clientdemo#5]
After updating Drive Kit from 5.0.0.307 to 5.2.0.300, I noticed that minSdkVersion increased to 29. 
I checked the functionality of our application after updating the library on version sdk 21 and everything works as it should.
Is there any reason why this was done and will the Drive Kit work up to 21 sdk? Is there any risk that something will not work?

**Comment by peura-toni** [comment]
Hi,

I have also updated the Drive Kit to version 5.2.0.300 and using SDK 21, but it works fine and I have not encountered any risks. In addition, the restriction on upgrading to SDK 29 can be removed with the "tools:overrideLibrary". You can check out [this document](https://developer.huawei.com/consumer/cn/forum/topic/0202599159806790684) for detailed information.

I hope it helps to solve your issue.
